{{
    config(
        materialized = 'table',
        schema = 'transformations',
        tags = ['thematiques', 'ropt']
    )
}}

WITH seg AS (
    SELECT
        ropt_id,
        -- Head (ordr=0)
        (array_agg(lc_codeext  ORDER BY ropt_ordr))[1]                  AS sro_nro,
        (array_agg(ti_codeext  ORDER BY ropt_ordr))[1]                  AS tiroir,
        (array_agg(cs_num      ORDER BY ropt_ordr))[1]                  AS cs_num,
        (array_agg(ps_numero   ORDER BY ropt_ordr))[1]                  AS ps_num,
        (array_agg(ps_fonct    ORDER BY ropt_ordr))[1]                  AS fonct,
        (array_agg(cb_codeext  ORDER BY ropt_ordr))[1]                  AS cable,
        (array_agg(cb_capafo   ORDER BY ropt_ordr))[1]                  AS capafo,
        (array_agg(fo_numtub   ORDER BY ropt_ordr))[1]                  AS tube,
        (array_agg(fo_nintub   ORDER BY ropt_ordr))[1]                  AS fo,
        (array_agg(ps_preaff   ORDER BY ropt_ordr))[1]                  AS preaff,
        (array_agg(cb_lgreel   ORDER BY ropt_ordr))[1]                  AS long,
        -- Segments (ordr >= 1)
        (array_agg(COALESCE(bp_codeext, lc_codeext) ORDER BY ropt_ordr))[2:24]  AS dest_candidates,
        (array_agg(COALESCE(bp_codeext, ti_codeext) ORDER BY ropt_ordr))[2:24]  AS bpe,
        (array_agg(ps_fonct    ORDER BY ropt_ordr))[2:24]                       AS foncts,
        (array_agg(cb_codeext  ORDER BY ropt_ordr))[2:24]                       AS cables,
        (array_agg(cb_capafo   ORDER BY ropt_ordr))[2:24]                       AS capafos,
        (array_agg(fo_numtub   ORDER BY ropt_ordr))[2:24]                       AS tubes,
        (array_agg(fo_nintub   ORDER BY ropt_ordr))[2:24]                       AS fos,
        (array_agg(ps_preaff   ORDER BY ropt_ordr))[2:24]                       AS preaffs,
        (array_agg(cb_lgreel   ORDER BY ropt_ordr))[2:24]                       AS longs,
        -- Sort keys (from head)
        (array_agg(ropt_typelog ORDER BY ropt_ordr))[1]                 AS ropt_typelog,
        (array_agg(lc_codeext  ORDER BY ropt_ordr))[1]                  AS sort_lc_codeext,
        (array_agg(ti_codeext  ORDER BY ropt_ordr))[1]                  AS sort_ti_codeext
    FROM {{ ref('ropt_section') }}
    GROUP BY ropt_id
)
SELECT
    sro_nro,
    tiroir,
    cs_num,
    ps_num,
    -- Last non-null segment → destination
    (
        SELECT v
        FROM unnest(seg.dest_candidates) WITH ORDINALITY AS u(v, i)
        WHERE v IS NOT NULL
        ORDER BY i DESC
        LIMIT 1
    ) AS destination,
    'R' || '_' || ropt_typelog || '_' || seg.ropt_id AS ropt_id,
    fonct,
    cable,
    capafo,
    tube,
    fo,
    preaff,
    long,
    bpe[1]                     AS bpe_1,
    foncts[1]                  AS fonct_1,
    cables[1]                  AS cable_1,
    capafos[1]                 AS capafo_1,
    tubes[1]                   AS tube_1,
    fos[1]                     AS fo_1,
    preaffs[1]                 AS preaff_1,
    longs[1]                   AS long_1,
    bpe[2]                     AS bpe_2,
    foncts[2]                  AS fonct_2,
    cables[2]                  AS cable_2,
    capafos[2]                 AS capafo_2,
    tubes[2]                   AS tube_2,
    fos[2]                     AS fo_2,
    preaffs[2]                 AS preaff_2,
    longs[2]                   AS long_2,
    bpe[3]                     AS bpe_3,
    foncts[3]                  AS fonct_3,
    cables[3]                  AS cable_3,
    capafos[3]                 AS capafo_3,
    tubes[3]                   AS tube_3,
    fos[3]                     AS fo_3,
    preaffs[3]                 AS preaff_3,
    longs[3]                   AS long_3,
    bpe[4]                     AS bpe_4,
    foncts[4]                  AS fonct_4,
    cables[4]                  AS cable_4,
    capafos[4]                 AS capafo_4,
    tubes[4]                   AS tube_4,
    fos[4]                     AS fo_4,
    preaffs[4]                 AS preaff_4,
    longs[4]                   AS long_4,
    bpe[5]                     AS bpe_5,
    foncts[5]                  AS fonct_5,
    cables[5]                  AS cable_5,
    capafos[5]                 AS capafo_5,
    tubes[5]                   AS tube_5,
    fos[5]                     AS fo_5,
    preaffs[5]                 AS preaff_5,
    longs[5]                   AS long_5,
    bpe[6]                     AS bpe_6,
    foncts[6]                  AS fonct_6,
    cables[6]                  AS cable_6,
    capafos[6]                 AS capafo_6,
    tubes[6]                   AS tube_6,
    fos[6]                     AS fo_6,
    preaffs[6]                 AS preaff_6,
    longs[6]                   AS long_6,
    bpe[7]                     AS bpe_7,
    foncts[7]                  AS fonct_7,
    cables[7]                  AS cable_7,
    capafos[7]                 AS capafo_7,
    tubes[7]                   AS tube_7,
    fos[7]                     AS fo_7,
    preaffs[7]                 AS preaff_7,
    longs[7]                   AS long_7,
    bpe[8]                     AS bpe_8,
    foncts[8]                  AS fonct_8,
    cables[8]                  AS cable_8,
    capafos[8]                 AS capafo_8,
    tubes[8]                   AS tube_8,
    fos[8]                     AS fo_8,
    preaffs[8]                 AS preaff_8,
    longs[8]                   AS long_8,
    bpe[9]                     AS bpe_9,
    foncts[9]                  AS fonct_9,
    cables[9]                  AS cable_9,
    capafos[9]                 AS capafo_9,
    tubes[9]                   AS tube_9,
    fos[9]                     AS fo_9,
    preaffs[9]                 AS preaff_9,
    longs[9]                   AS long_9,
    bpe[10]                    AS bpe_10,
    foncts[10]                 AS fonct_10,
    cables[10]                 AS cable_10,
    capafos[10]                AS capafo_10,
    tubes[10]                  AS tube_10,
    fos[10]                    AS fo_10,
    preaffs[10]                AS preaff_10,
    longs[10]                  AS long_10,
    bpe[11]                    AS bpe_11,
    foncts[11]                 AS fonct_11,
    cables[11]                 AS cable_11,
    capafos[11]                AS capafo_11,
    tubes[11]                  AS tube_11,
    fos[11]                    AS fo_11,
    preaffs[11]                AS preaff_11,
    longs[11]                  AS long_11,
    bpe[12]                    AS bpe_12,
    foncts[12]                 AS fonct_12,
    cables[12]                 AS cable_12,
    capafos[12]                AS capafo_12,
    tubes[12]                  AS tube_12,
    fos[12]                    AS fo_12,
    preaffs[12]                AS preaff_12,
    longs[12]                  AS long_12,
    bpe[13]                    AS bpe_13,
    foncts[13]                 AS fonct_13,
    cables[13]                 AS cable_13,
    capafos[13]                AS capafo_13,
    tubes[13]                  AS tube_13,
    fos[13]                    AS fo_13,
    preaffs[13]                AS preaff_13,
    longs[13]                  AS long_13,
    bpe[14]                    AS bpe_14,
    foncts[14]                 AS fonct_14,
    cables[14]                 AS cable_14,
    capafos[14]                AS capafo_14,
    tubes[14]                  AS tube_14,
    fos[14]                    AS fo_14,
    preaffs[14]                AS preaff_14,
    longs[14]                  AS long_14,
    bpe[15]                    AS bpe_15,
    foncts[15]                 AS fonct_15,
    cables[15]                 AS cable_15,
    capafos[15]                AS capafo_15,
    tubes[15]                  AS tube_15,
    fos[15]                    AS fo_15,
    preaffs[15]                AS preaff_15,
    longs[15]                  AS long_15,
    bpe[16]                    AS bpe_16,
    foncts[16]                 AS fonct_16,
    cables[16]                 AS cable_16,
    capafos[16]                AS capafo_16,
    tubes[16]                  AS tube_16,
    fos[16]                    AS fo_16,
    preaffs[16]                AS preaff_16,
    longs[16]                  AS long_16,
    bpe[17]                    AS bpe_17,
    foncts[17]                 AS fonct_17,
    cables[17]                 AS cable_17,
    capafos[17]                AS capafo_17,
    tubes[17]                  AS tube_17,
    fos[17]                    AS fo_17,
    preaffs[17]                AS preaff_17,
    longs[17]                  AS long_17,
    bpe[18]                    AS bpe_18,
    foncts[18]                 AS fonct_18,
    cables[18]                 AS cable_18,
    capafos[18]                AS capafo_18,
    tubes[18]                  AS tube_18,
    fos[18]                    AS fo_18,
    preaffs[18]                AS preaff_18,
    longs[18]                  AS long_18,
    bpe[19]                    AS bpe_19,
    foncts[19]                 AS fonct_19,
    cables[19]                 AS cable_19,
    capafos[19]                AS capafo_19,
    tubes[19]                  AS tube_19,
    fos[19]                    AS fo_19,
    preaffs[19]                AS preaff_19,
    longs[19]                  AS long_19,
    bpe[20]                    AS bpe_20,
    foncts[20]                 AS fonct_20,
    cables[20]                 AS cable_20,
    capafos[20]                AS capafo_20,
    tubes[20]                  AS tube_20,
    fos[20]                    AS fo_20,
    preaffs[20]                AS preaff_20,
    longs[20]                  AS long_20,
    bpe[21]                    AS bpe_21,
    foncts[21]                 AS fonct_21,
    cables[21]                 AS cable_21,
    capafos[21]                AS capafo_21,
    tubes[21]                  AS tube_21,
    fos[21]                    AS fo_21,
    preaffs[21]                AS preaff_21,
    longs[21]                  AS long_21,
    bpe[22]                    AS bpe_22,
    foncts[22]                 AS fonct_22,
    cables[22]                 AS cable_22,
    capafos[22]                AS capafo_22,
    tubes[22]                  AS tube_22,
    fos[22]                    AS fo_22,
    preaffs[22]                AS preaff_22,
    longs[22]                  AS long_22,
    bpe[23]                    AS bpe_23,
    foncts[23]                 AS fonct_23,
    cables[23]                 AS cable_23,
    capafos[23]                AS capafo_23,
    tubes[23]                  AS tube_23,
    fos[23]                    AS fo_23,
    preaffs[23]                AS preaff_23,
    longs[23]                  AS long_23
FROM seg
ORDER BY
    CASE ropt_typelog
        WHEN 'DI' THEN 1
        WHEN 'TR' THEN 2
        WHEN 'CT' THEN 3
        ELSE 4
    END,
    sort_lc_codeext ASC,
    sort_ti_codeext ASC,
    cs_num,
    ps_num ASC
