{{
    config(
        materialized = 'table',
        schema = 'transformations',
        tags = ['thematiques', 'ropt']
    )
}}

SELECT
    s0.lc_codeext AS sro_nro,
    s0.ti_codeext AS tiroir,
    s0.cs_num AS cs_num,
    s0.ps_numero AS ps_num,
    COALESCE(
        COALESCE(s23.bp_codeext, s23.lc_codeext),
        COALESCE(s22.bp_codeext, s22.lc_codeext),
        COALESCE(s21.bp_codeext, s21.lc_codeext),
        COALESCE(s20.bp_codeext, s20.lc_codeext),
        COALESCE(s19.bp_codeext, s19.lc_codeext),
        COALESCE(s18.bp_codeext, s18.lc_codeext),
        COALESCE(s17.bp_codeext, s17.lc_codeext),
        COALESCE(s16.bp_codeext, s16.lc_codeext),
        COALESCE(s15.bp_codeext, s15.lc_codeext),
        COALESCE(s14.bp_codeext, s14.lc_codeext),
        COALESCE(s13.bp_codeext, s13.lc_codeext),
        COALESCE(s12.bp_codeext, s12.lc_codeext),
        COALESCE(s11.bp_codeext, s11.lc_codeext),
        COALESCE(s10.bp_codeext, s10.lc_codeext),
        COALESCE(s9.bp_codeext, s9.lc_codeext),
        COALESCE(s8.bp_codeext, s8.lc_codeext),
        COALESCE(s7.bp_codeext, s7.lc_codeext),
        COALESCE(s6.bp_codeext, s6.lc_codeext),
        COALESCE(s5.bp_codeext, s5.lc_codeext),
        COALESCE(s4.bp_codeext, s4.lc_codeext),
        COALESCE(s3.bp_codeext, s3.lc_codeext),
        COALESCE(s2.bp_codeext, s2.lc_codeext),
        COALESCE(s1.bp_codeext, s1.lc_codeext)
    ) AS destination,
    'R' || '_' || s0.ropt_typelog || '_' || s0.ropt_id AS ropt_id,
    s0.ps_fonct AS fonct,
    s0.cb_codeext AS cable,
    s0.cb_capafo AS capafo,
    s0.fo_numtub AS tube,
    s0.fo_nintub AS fo,
    s0.ps_preaff AS preaff,
    s0.cb_lgreel AS long,
    COALESCE(s1.bp_codeext, s1.ti_codeext) AS bpe_1,
    s1.ps_fonct AS fonct_1,
    s1.cb_codeext AS cable_1,
    s1.cb_capafo AS capafo_1,
    s1.fo_numtub AS tube_1,
    s1.fo_nintub AS fo_1,
    s1.ps_preaff AS preaff_1,
    s1.cb_lgreel AS long_1,
    COALESCE(s2.bp_codeext, s2.ti_codeext) AS bpe_2,
    s2.ps_fonct AS fonct_2,
    s2.cb_codeext AS cable_2,
    s2.cb_capafo AS capafo_2,
    s2.fo_numtub AS tube_2,
    s2.fo_nintub AS fo_2,
    s2.ps_preaff AS preaff_2,
    s2.cb_lgreel AS long_2,
    COALESCE(s3.bp_codeext, s3.ti_codeext) AS bpe_3,
    s3.ps_fonct AS fonct_3,
    s3.cb_codeext AS cable_3,
    s3.cb_capafo AS capafo_3,
    s3.fo_numtub AS tube_3,
    s3.fo_nintub AS fo_3,
    s3.ps_preaff AS preaff_3,
    s3.cb_lgreel AS long_3,
    COALESCE(s4.bp_codeext, s4.ti_codeext) AS bpe_4,
    s4.ps_fonct AS fonct_4,
    s4.cb_codeext AS cable_4,
    s4.cb_capafo AS capafo_4,
    s4.fo_numtub AS tube_4,
    s4.fo_nintub AS fo_4,
    s4.ps_preaff AS preaff_4,
    s4.cb_lgreel AS long_4,
    COALESCE(s5.bp_codeext, s5.ti_codeext) AS bpe_5,
    s5.ps_fonct AS fonct_5,
    s5.cb_codeext AS cable_5,
    s5.cb_capafo AS capafo_5,
    s5.fo_numtub AS tube_5,
    s5.fo_nintub AS fo_5,
    s5.ps_preaff AS preaff_5,
    s5.cb_lgreel AS long_5,
    COALESCE(s6.bp_codeext, s6.ti_codeext) AS bpe_6,
    s6.ps_fonct AS fonct_6,
    s6.cb_codeext AS cable_6,
    s6.cb_capafo AS capafo_6,
    s6.fo_numtub AS tube_6,
    s6.fo_nintub AS fo_6,
    s6.ps_preaff AS preaff_6,
    s6.cb_lgreel AS long_6,
    COALESCE(s7.bp_codeext, s7.ti_codeext) AS bpe_7,
    s7.ps_fonct AS fonct_7,
    s7.cb_codeext AS cable_7,
    s7.cb_capafo AS capafo_7,
    s7.fo_numtub AS tube_7,
    s7.fo_nintub AS fo_7,
    s7.ps_preaff AS preaff_7,
    s7.cb_lgreel AS long_7,
    COALESCE(s8.bp_codeext, s8.ti_codeext) AS bpe_8,
    s8.ps_fonct AS fonct_8,
    s8.cb_codeext AS cable_8,
    s8.cb_capafo AS capafo_8,
    s8.fo_numtub AS tube_8,
    s8.fo_nintub AS fo_8,
    s8.ps_preaff AS preaff_8,
    s8.cb_lgreel AS long_8,
    COALESCE(s9.bp_codeext, s9.ti_codeext) AS bpe_9,
    s9.ps_fonct AS fonct_9,
    s9.cb_codeext AS cable_9,
    s9.cb_capafo AS capafo_9,
    s9.fo_numtub AS tube_9,
    s9.fo_nintub AS fo_9,
    s9.ps_preaff AS preaff_9,
    s9.cb_lgreel AS long_9,
    COALESCE(s10.bp_codeext, s10.ti_codeext) AS bpe_10,
    s10.ps_fonct AS fonct_10,
    s10.cb_codeext AS cable_10,
    s10.cb_capafo AS capafo_10,
    s10.fo_numtub AS tube_10,
    s10.fo_nintub AS fo_10,
    s10.ps_preaff AS preaff_10,
    s10.cb_lgreel AS long_10,
    COALESCE(s11.bp_codeext, s11.ti_codeext) AS bpe_11,
    s11.ps_fonct AS fonct_11,
    s11.cb_codeext AS cable_11,
    s11.cb_capafo AS capafo_11,
    s11.fo_numtub AS tube_11,
    s11.fo_nintub AS fo_11,
    s11.ps_preaff AS preaff_11,
    s11.cb_lgreel AS long_11,
    COALESCE(s12.bp_codeext, s12.ti_codeext) AS bpe_12,
    s12.ps_fonct AS fonct_12,
    s12.cb_codeext AS cable_12,
    s12.cb_capafo AS capafo_12,
    s12.fo_numtub AS tube_12,
    s12.fo_nintub AS fo_12,
    s12.ps_preaff AS preaff_12,
    s12.cb_lgreel AS long_12,
    COALESCE(s13.bp_codeext, s13.ti_codeext) AS bpe_13,
    s13.ps_fonct AS fonct_13,
    s13.cb_codeext AS cable_13,
    s13.cb_capafo AS capafo_13,
    s13.fo_numtub AS tube_13,
    s13.fo_nintub AS fo_13,
    s13.ps_preaff AS preaff_13,
    s13.cb_lgreel AS long_13,
    COALESCE(s14.bp_codeext, s14.ti_codeext) AS bpe_14,
    s14.ps_fonct AS fonct_14,
    s14.cb_codeext AS cable_14,
    s14.cb_capafo AS capafo_14,
    s14.fo_numtub AS tube_14,
    s14.fo_nintub AS fo_14,
    s14.ps_preaff AS preaff_14,
    s14.cb_lgreel AS long_14,
    COALESCE(s15.bp_codeext, s15.ti_codeext) AS bpe_15,
    s15.ps_fonct AS fonct_15,
    s15.cb_codeext AS cable_15,
    s15.cb_capafo AS capafo_15,
    s15.fo_numtub AS tube_15,
    s15.fo_nintub AS fo_15,
    s15.ps_preaff AS preaff_15,
    s15.cb_lgreel AS long_15,
    COALESCE(s16.bp_codeext, s16.ti_codeext) AS bpe_16,
    s16.ps_fonct AS fonct_16,
    s16.cb_codeext AS cable_16,
    s16.cb_capafo AS capafo_16,
    s16.fo_numtub AS tube_16,
    s16.fo_nintub AS fo_16,
    s16.ps_preaff AS preaff_16,
    s16.cb_lgreel AS long_16,
    COALESCE(s17.bp_codeext, s17.ti_codeext) AS bpe_17,
    s17.ps_fonct AS fonct_17,
    s17.cb_codeext AS cable_17,
    s17.cb_capafo AS capafo_17,
    s17.fo_numtub AS tube_17,
    s17.fo_nintub AS fo_17,
    s17.ps_preaff AS preaff_17,
    s17.cb_lgreel AS long_17,
    COALESCE(s18.bp_codeext, s18.ti_codeext) AS bpe_18,
    s18.ps_fonct AS fonct_18,
    s18.cb_codeext AS cable_18,
    s18.cb_capafo AS capafo_18,
    s18.fo_numtub AS tube_18,
    s18.fo_nintub AS fo_18,
    s18.ps_preaff AS preaff_18,
    s18.cb_lgreel AS long_18,
    COALESCE(s19.bp_codeext, s19.ti_codeext) AS bpe_19,
    s19.ps_fonct AS fonct_19,
    s19.cb_codeext AS cable_19,
    s19.cb_capafo AS capafo_19,
    s19.fo_numtub AS tube_19,
    s19.fo_nintub AS fo_19,
    s19.ps_preaff AS preaff_19,
    s19.cb_lgreel AS long_19,
    COALESCE(s20.bp_codeext, s20.ti_codeext) AS bpe_20,
    s20.ps_fonct AS fonct_20,
    s20.cb_codeext AS cable_20,
    s20.cb_capafo AS capafo_20,
    s20.fo_numtub AS tube_20,
    s20.fo_nintub AS fo_20,
    s20.ps_preaff AS preaff_20,
    s20.cb_lgreel AS long_20,
    COALESCE(s21.bp_codeext, s21.ti_codeext) AS bpe_21,
    s21.ps_fonct AS fonct_21,
    s21.cb_codeext AS cable_21,
    s21.cb_capafo AS capafo_21,
    s21.fo_numtub AS tube_21,
    s21.fo_nintub AS fo_21,
    s21.ps_preaff AS preaff_21,
    s21.cb_lgreel AS long_21,
    COALESCE(s22.bp_codeext, s22.ti_codeext) AS bpe_22,
    s22.ps_fonct AS fonct_22,
    s22.cb_codeext AS cable_22,
    s22.cb_capafo AS capafo_22,
    s22.fo_numtub AS tube_22,
    s22.fo_nintub AS fo_22,
    s22.ps_preaff AS preaff_22,
    s22.cb_lgreel AS long_22,
    COALESCE(s23.bp_codeext, s23.ti_codeext) AS bpe_23,
    s23.ps_fonct AS fonct_23,
    s23.cb_codeext AS cable_23,
    s23.cb_capafo AS capafo_23,
    s23.fo_numtub AS tube_23,
    s23.fo_nintub AS fo_23,
    s23.ps_preaff AS preaff_23,
    s23.cb_lgreel AS long_23
FROM {{ ref('ropt_section') }} s0
LEFT JOIN {{ ref('ropt_section') }} s1 ON s1.ropt_id = s0.ropt_id AND s1.ropt_ordr = s0.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s2 ON s2.ropt_id = s0.ropt_id AND s2.ropt_ordr = s1.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s3 ON s3.ropt_id = s0.ropt_id AND s3.ropt_ordr = s2.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s4 ON s4.ropt_id = s0.ropt_id AND s4.ropt_ordr = s3.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s5 ON s5.ropt_id = s0.ropt_id AND s5.ropt_ordr = s4.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s6 ON s6.ropt_id = s0.ropt_id AND s6.ropt_ordr = s5.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s7 ON s7.ropt_id = s0.ropt_id AND s7.ropt_ordr = s6.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s8 ON s8.ropt_id = s0.ropt_id AND s8.ropt_ordr = s7.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s9 ON s9.ropt_id = s0.ropt_id AND s9.ropt_ordr = s8.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s10 ON s10.ropt_id = s0.ropt_id AND s10.ropt_ordr = s9.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s11 ON s11.ropt_id = s0.ropt_id AND s11.ropt_ordr = s10.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s12 ON s12.ropt_id = s0.ropt_id AND s12.ropt_ordr = s11.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s13 ON s13.ropt_id = s0.ropt_id AND s13.ropt_ordr = s12.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s14 ON s14.ropt_id = s0.ropt_id AND s14.ropt_ordr = s13.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s15 ON s15.ropt_id = s0.ropt_id AND s15.ropt_ordr = s14.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s16 ON s16.ropt_id = s0.ropt_id AND s16.ropt_ordr = s15.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s17 ON s17.ropt_id = s0.ropt_id AND s17.ropt_ordr = s16.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s18 ON s18.ropt_id = s0.ropt_id AND s18.ropt_ordr = s17.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s19 ON s19.ropt_id = s0.ropt_id AND s19.ropt_ordr = s18.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s20 ON s20.ropt_id = s0.ropt_id AND s20.ropt_ordr = s19.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s21 ON s21.ropt_id = s0.ropt_id AND s21.ropt_ordr = s20.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s22 ON s22.ropt_id = s0.ropt_id AND s22.ropt_ordr = s21.ropt_ordr + 1
LEFT JOIN {{ ref('ropt_section') }} s23 ON s23.ropt_id = s0.ropt_id AND s23.ropt_ordr = s22.ropt_ordr + 1
WHERE s0.ropt_ordr = 0
ORDER BY CASE s0.ropt_typelog
    WHEN 'DI' THEN 1
    WHEN 'TR' THEN 2
    WHEN 'CT' THEN 3
    ELSE 4
END,
    s0.lc_codeext ASC,
    s0.ti_codeext ASC,
    s0.cs_num,
    s0.ps_numero ASC
